version: '3.8'

services:

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    restart: always
    volumes:
      - ./collector/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml:cached
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 5078:5078 # OTLP   gRPC receiver
      - 5079:5079 # OTLP/2 gRPC receiver

  openobserve:
    image: openobserve/openobserve
    volumes:
      - ob-v:/data
    ports:
      - 5080:5080
      - 5081:5081
    environment:
      - ZO_DATA_DIR=/data
      - ZO_ROOT_USER_EMAIL=zhangshanyou@ai4c.cn
      - ZO_ROOT_USER_PASSWORD=geffzhang
      - TZ=Asia/Shanghai
    restart: always

  aspire:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard
    restart: unless-stopped
    ports:
      - 18888:18888

# Traces are ephemeral.
# Logs and metrics are persisted.
volumes:
  ob-v: {}
