receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:5079
  otlp/2:
    protocols:
      grpc:
        endpoint: 0.0.0.0:5078

processors:
  batch:

exporters:

  otlphttp/openobserve:
    endpoint: http://openobserve:5080/api/default/
    headers:
      Authorization: Basic emhhbmdzaGFueW91QGFpNGMuY246YlBsbFBtMXJ1VTdNeU1oaw==
      stream-name: default
  otlp/openobserve:
    endpoint: openobserve:5081
    headers:
      Authorization: "Basic emhhbmdzaGFueW91QGFpNGMuY246YlBsbFBtMXJ1VTdNeU1oaw=="
      organization: default
      stream-name: default
    tls:
      insecure: true

  otlp/aspire:
    endpoint: aspire:18889
    tls:
      insecure: true

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/openobserve, otlp/aspire]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/openobserve, otlp/aspire]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/openobserve, otlp/aspire]
    traces/2:
      receivers: [otlp/2]
      processors: [batch]
      exporters: [ otlp/openobserve, otlp/aspire]
    metrics/2:
      receivers: [otlp/2]
      processors: [batch]
      exporters: [otlp/openobserve, otlp/aspire]
    logs/2:
      receivers: [otlp/2]
      processors: [batch]
      exporters: [otlp/openobserve, otlp/aspire]


